#!/bin/sh
set -e

case "$1" in
    purge|abort-install|disappear)
        deb-systemd-invoke restart 'logrotate.service' >/dev/null || true

        if [ -f /usr/share/debconf/confmodule ]; then
            . /usr/share/debconf/confmodule
            db_purge
            db_stop
        fi
        ;;
esac

exit 0